#!/usr/bin/env bash
# Pi media center
source ./profiles/min

FEAT_GUI=1
FEAT_GENERATE_KEYS=1

if [[ "${OSTYPE}" != "linux-gnu" ]]; then
    error "This profile expects linux"
fi

add_pkgs linux "kodi chromium kodi-inputstream-adaptive"
