#!/usr/bin/env bash
# Pi media center
source ./profiles/min

FEAT_GUI=1
FEAT_GENERATE_KEYS=1

if [[ "$(uname)" != "Linux" ]]; then
    error "This profile expects linux"
fi

add_pkgs --linux "kodi kodi-inputstream-adaptive rsync"
add_pkgs --apt "unattended-upgrades ufw python3-pycryptodome build-essential"

post_bootstrap() {
    # Generate certs to have web interface over TLS
    ./scripts/kodi-generate-certs.sh
}
